### ISSUE TITLE
Add authorization by password

### ISSUE THREAD

**Issue by paolosezart** [terrylao/WinCat#1]
Request to the developer. Add to this tool the ability to connect to a remote computer by password.
Thanks!

**Comment by terrylao** [comment]
ADD SSH SUPPORT?

**Comment by paolosezart** [comment]
No, I mean the connection password to run a remote program, (cmd.exe in the example). 
For example, I have computer "A" connect to computer "B" (192.168.1.10):

computer A (client):
`wnc.exe 192.168.1.10 8118`

comp B (server):
`wnc.exe -lk -e "cmd" 8118`

I would like to be able to set a password to access computer "B". For example:

Comp A (client):
`wnc.exe 192.168.1.10 8118 -p P@55W0RD`

comp B (server):
`wnc.exe -lk -e "cmd" 8118 -p P@55W0RD`

**Comment by terrylao** [comment]
the OTP function for -C was ready, but not for -e

**Comment by terrylao** [comment]
added
