### ISSUE TITLE
Hello, may I ask if the UDP port can be tested

### ISSUE THREAD

**Issue by HeliusHao** [terrylao/WinCat#2]
Hello, may I ask if the UDP port can be tested

**Comment by terrylao** [comment]
UDP server was ready, but not integrate into main.cc

**Comment by HeliusHao** [comment]
I hope the new version of UDP functionality will be released as soon as possible. Thank you



***@***.***
 
From: Terry Lao
Date: 2024-01-15 22:44
To: terrylao/WinCat
CC: Helius; Author
Subject: Re: [terrylao/WinCat] Hello, may I ask if the UDP port can be tested (Issue #2)
UDP server was ready, but not integrate into main.cc

**Comment by terrylao** [comment]
added
